"""add coaching_cache table

Revision ID: 5f05c74ee344
Revises: d3c282e952de
Create Date: 2026-07-22 14:02:04.002835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f05c74ee344'
down_revision: Union[str, Sequence[str], None] = 'd3c282e952de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaching_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('generated_date', sa.String(length=10), nullable=False),
    sa.Column('messages_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaching_cache_id'), 'coaching_cache', ['id'], unique=False)
    op.create_index(op.f('ix_coaching_cache_user_id'), 'coaching_cache', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coaching_cache_user_id'), table_name='coaching_cache')
    op.drop_index(op.f('ix_coaching_cache_id'), table_name='coaching_cache')
    op.drop_table('coaching_cache')
    # ### end Alembic commands ###
