"""add composite index on health_records user_id date

Revision ID: c1df83b2dad1
Revises: 387f68806524
Create Date: 2026-07-22 17:42:50.907509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1df83b2dad1'
down_revision: Union[str, Sequence[str], None] = '387f68806524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_health_records_user_id_date', 'health_records', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_records_user_id_date', table_name='health_records')
    # ### end Alembic commands ###
